name: Build

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu_x86_64:
    name: Build on Ubuntu x86_64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache_ubuntu_x86_64

    - name: Build Hangover on x86_64
      run: |
        docker run --rm -i -v $PWD:/root -v ~/.ccache:/root/.ccache --cpus $(nproc) --name x86_64_build amd64/ubuntu:jammy bash <<EOF

        apt update
        apt install -y curl sudo

        pushd /root
        ./build.sh --arch=x86_64
        popd

        EOF

  ubuntu_arm64:
    name: Build on Ubuntu arm64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache_ubuntu_arm64

    - name: Build Hangover on arm64
      run: |
        docker run --rm -i -v $PWD:/root -v ~/.ccache:/root/.ccache --cpus $(nproc) --name arm64_build arm64v8/ubuntu:jammy bash <<EOF

        apt update
        apt install -y curl sudo

        pushd /root
        ./build.sh --arch=arm64
        popd

        EOF
